'use strict';
const LABEL_SIZES={small:{width:'75mm',height:'50mm',fontSize:'7pt',picSize:'14mm',name:'75×50mm (bottle)'},medium:{width:'100mm',height:'75mm',fontSize:'8pt',picSize:'18mm',name:'100×75mm (container)'},large:{width:'148mm',height:'105mm',fontSize:'10pt',picSize:'24mm',name:'148×105mm (drum)'},a4:{width:'210mm',height:'297mm',fontSize:'11pt',picSize:'32mm',name:'A4 (storage cabinet)'}};
const GHS_EMOJI={GHS01:'💥',GHS02:'🔥',GHS03:'🔥',GHS04:'🔴',GHS05:'⚗️',GHS06:'☠️',GHS07:'❗',GHS08:'⚕️',GHS09:'🌿'};

const extractLabelData=(sdsDoc)=>{const secs=sdsDoc.sections||{};const s1=secs.section1?.content||{};const s2=secs.section2?.content||{};const hS=s2.hazard_statements||[];const pAll=[...(s2.precautionary_statements?.prevention||[]),...(s2.precautionary_statements?.response||[]),...(s2.precautionary_statements?.storage||[]),...(s2.precautionary_statements?.disposal||[])];return{product_name:sdsDoc.chemical_name||'Unknown Chemical',product_identifier:s1.product_identifier||sdsDoc.chemical_name,cas_number:sdsDoc.cas_number||'',signal_word:s2.signal_word||'WARNING',pictograms:s2.pictograms||[],hazard_statements:Array.isArray(hS)?hS:[hS],precautionary_statements:pAll.slice(0,8),supplier_name:s1.supplier_name||'Supplier Name',supplier_address:s1.supplier_address||'',supplier_phone:s1.supplier_phone||'',emergency_phone:s1.emergency_phone||'CHEMTREC: +1-800-424-9300',other_hazards:s2.other_hazards||'',language:sdsDoc.language||'en'};};

const generateLabelHtml=(sdsDoc,size='medium',language='en')=>{const data=extractLabelData(sdsDoc);const dims=LABEL_SIZES[size]||LABEL_SIZES.medium;const isRTL=['ar','ur'].includes(language);const isDanger=(data.signal_word||'').toUpperCase()==='DANGER';
const picHtml=(data.pictograms||[]).slice(0,4).map(code=>{const c=code.split(' ')[0];return `<div style="display:inline-block;width:${dims.picSize};height:${dims.picSize};margin:1mm;border:2px solid #000;border-radius:2px;text-align:center;line-height:${dims.picSize};font-size:20px">${GHS_EMOJI[c]||'⚠'}</div>`;}).join('');
const hHtml=(data.hazard_statements||[]).slice(0,6).map(h=>`<p style="margin:0.5mm 0;font-size:${dims.fontSize}">${h}</p>`).join('');
const pHtml=(data.precautionary_statements||[]).slice(0,5).map(p=>`<p style="margin:0.5mm 0;font-size:${dims.fontSize}">${p}</p>`).join('');
return `<!DOCTYPE html><html lang="${language}" dir="${isRTL?'rtl':'ltr'}"><head><meta charset="UTF-8"><style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:${isRTL?"'Noto Sans Arabic',":''}Arial,sans-serif;background:#fff}.label{width:${dims.width};min-height:${dims.height};border:2.5px solid #000;padding:3mm;background:#fff}.name{font-size:calc(${dims.fontSize} + 3pt);font-weight:700;text-align:center;margin-bottom:1mm}.signal{font-size:calc(${dims.fontSize} + 5pt);font-weight:900;text-align:center;color:${isDanger?'#c0392b':'#e67e22'};letter-spacing:2px;margin:1.5mm 0;border:1.5px solid ${isDanger?'#c0392b':'#e67e22'};padding:1mm}.pics{text-align:center;margin:2mm 0}.sec{margin:1.5mm 0;border-top:0.5px solid #ccc;padding-top:1mm}.sec-lbl{font-size:calc(${dims.fontSize} - 1pt);font-weight:700;text-transform:uppercase;color:#555}.sup{border-top:1.5px solid #000;margin-top:2mm;padding-top:1.5mm;font-size:calc(${dims.fontSize} - 1pt)}@media print{@page{size:${dims.width} auto;margin:0}}</style></head><body><div class="label"><div class="name">${data.product_name}</div>${data.cas_number?`<p style="text-align:center;font-size:${dims.fontSize};color:#555">CAS: ${data.cas_number}</p>`:''}<div class="signal">${data.signal_word?.toUpperCase()||'WARNING'}</div><div class="pics">${picHtml||`<span style="font-size:9pt;color:#999">No pictograms</span>`}</div>${hHtml?`<div class="sec"><p class="sec-lbl">⚠ Hazard Statements</p>${hHtml}</div>`:''} ${pHtml?`<div class="sec"><p class="sec-lbl">Precautionary Statements</p>${pHtml}</div>`:''} ${data.other_hazards?`<div class="sec"><p style="font-size:${dims.fontSize};font-style:italic">${data.other_hazards}</p></div>`:''}<div class="sup"><strong>${data.supplier_name}</strong><br>${data.supplier_address?`${data.supplier_address}<br>`:''} ${data.supplier_phone?`Tel: ${data.supplier_phone}<br>`:''}<strong>Emergency: ${data.emergency_phone}</strong></div></div></body></html>`;};

module.exports={generateLabelHtml,extractLabelData,LABEL_SIZES};
