import { z } from 'zod';

const metricSchema = z.object({
  value: z.number(),
  previousValue: z.number().optional(),
  percentChange: z.number().optional(),
  trend: z.enum(['up', 'down', 'flat']).optional(),
  status: z.enum(['good', 'warning', 'critical', 'neutral']).optional(),
  href: z.string().optional(),
});

export const dashboardSummarySchema = z.object({
  scope: z.object({
    organizationName: z.string(),
    siteName: z.string().optional(),
    role: z.enum(['admin', 'ehs_manager', 'worker']),
  }),
  generatedAt: z.string(),
  kpis: z.object({
    totalSds: metricSchema,
    approvedSds: metricSchema,
    complianceScore: metricSchema,
    criticalIssues: metricSchema,
    pendingApprovals: metricSchema,
    expiringSoon: metricSchema,
    regulatoryImpact: metricSchema,
    pipelineHealth: metricSchema,
  }),
  complianceTrend: z.array(z.object({ date: z.string(), score: z.number(), threshold: z.number() })),
  complianceBreakdown: z.array(z.object({
    key: z.string(),
    label: z.string(),
    score: z.number(),
    change: z.number(),
    status: z.enum(['good', 'warning', 'critical', 'neutral']),
    href: z.string(),
  })),
  lifecycleDistribution: z.array(z.object({
    status: z.enum(['draft', 'submitted', 'technical_review', 'regulatory_review', 'changes_requested', 'approved', 'published', 'expired', 'superseded', 'archived']),
    label: z.string(),
    count: z.number(),
  })),
  myTasks: z.array(z.object({
    id: z.string(),
    type: z.enum(['technical_review', 'regulatory_review', 'approval', 'validation_issue', 'compliance_action', 'regulatory_acknowledgement', 'sds_expiry_review', 'supplier_follow_up', 'pipeline_intervention', 'sop_acknowledgement']),
    title: z.string(),
    relatedEntityLabel: z.string(),
    priority: z.enum(['low', 'medium', 'high', 'critical']),
    status: z.enum(['open', 'in_progress', 'blocked', 'completed', 'overdue']),
    dueAt: z.string().optional(),
    assignedRole: z.string(),
    href: z.string(),
    actionLabel: z.string(),
  })),
  criticalIssues: z.array(z.object({
    id: z.string(),
    title: z.string(),
    severity: z.enum(['info', 'minor', 'major', 'critical']),
    source: z.enum(['validation', 'compliance', 'regulatory', 'data_quality']),
    ruleId: z.string().optional(),
    sdsId: z.string(),
    sdsName: z.string(),
    sectionNumber: z.number().optional(),
    jurisdiction: z.string().optional(),
    ownerName: z.string().optional(),
    detectedAt: z.string(),
    status: z.enum(['open', 'assigned', 'in_progress', 'resolved', 'overridden']),
    href: z.string(),
  })),
  recentSdsActivity: z.array(z.object({
    id: z.string(),
    product: z.string(),
    identifier: z.string(),
    version: z.number(),
    jurisdiction: z.string(),
    language: z.string(),
    status: z.string(),
    complianceScore: z.number().optional(),
    owner: z.string(),
    updatedAt: z.string(),
    updatedBy: z.string(),
    href: z.string(),
  })),
  regulatoryImpact: z.array(z.object({
    id: z.string(),
    framework: z.string(),
    jurisdiction: z.string(),
    title: z.string(),
    effectiveDate: z.string().optional(),
    severity: z.enum(['informational', 'action_required', 'deadline_approaching', 'critical']),
    affectedSubstances: z.number(),
    affectedSds: z.number(),
    affectedLabels: z.number(),
    requiredAction: z.string(),
    owner: z.string(),
    status: z.string(),
    href: z.string(),
  })),
  pipelineHealth: z.object({
    jobsToday: z.number(),
    successRate: z.number(),
    averageDurationMinutes: z.number(),
    running: z.number(),
    waiting: z.number(),
    failed: z.number(),
    manualReview: z.number(),
    deadLetter: z.number(),
  }),
  recentPipelineJobs: z.array(z.object({
    id: z.string(),
    inputType: z.string(),
    relatedDocument: z.string(),
    currentStage: z.string(),
    progress: z.number(),
    startedAt: z.string().optional(),
    durationMinutes: z.number().optional(),
    status: z.enum(['running', 'waiting', 'failed', 'blocked', 'complete']),
    retryCount: z.number(),
    href: z.string(),
  })),
  approvalWorkload: z.object({
    technicalReview: z.number(),
    regulatoryReview: z.number(),
    finalApproval: z.number(),
    changesRequested: z.number(),
    overdue: z.number(),
    averageTurnaroundHours: z.number(),
    reviewers: z.array(z.object({
      id: z.string(),
      name: z.string(),
      assignedCount: z.number(),
      overdueCount: z.number(),
      averageCompletionHours: z.number(),
    })),
  }),
  upcomingReviews: z.array(z.object({
    id: z.string(),
    product: z.string(),
    version: z.number(),
    jurisdiction: z.string(),
    reviewDate: z.string(),
    owner: z.string(),
    riskLevel: z.enum(['low', 'medium', 'high', 'critical']),
    href: z.string(),
  })),
  dataQuality: z.object({
    missingSources: z.number(),
    lowConfidenceFields: z.number(),
    unverifiedAiValues: z.number(),
    duplicateCandidates: z.number(),
    missingOwner: z.number(),
    missingReviewDate: z.number(),
    productsWithoutPublishedSds: z.number(),
    labelsOutOfSync: z.number(),
  }),
  activityFeed: z.array(z.object({
    id: z.string(),
    actor: z.string(),
    action: z.string(),
    objectLabel: z.string(),
    timestamp: z.string(),
    scope: z.string(),
    status: z.string().optional(),
    href: z.string(),
  })),
});
