'use client';
import type { SopDocument } from '@/types/sop.types';

export default function SopPrintView({ sop }: { sop: SopDocument }) {
  const c = sop.content;
  const isRTL = sop.isRtl || sop.language === 'ar';
  return (
    <div dir={isRTL ? 'rtl' : 'ltr'} className="p-8 max-w-2xl mx-auto print:p-4">
      <div className="border-b-2 border-gray-900 pb-4 mb-6">
        <h1 className="text-xl font-bold text-gray-900">{c.title}</h1>
        <p className="text-sm text-gray-600 mt-1">{c.chemicalName} · SOP v{sop.version} · {c.effectiveDate}</p>
      </div>
      {c.requiredPpe?.length > 0 && (
        <div className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wide text-gray-700 mb-2">Required PPE</h2>
          <div className="grid grid-cols-2 gap-2">
            {c.requiredPpe.map((p, i) => (
              <div key={i} className="border border-gray-200 rounded p-2">
                <p className="text-xs font-semibold">{p.item}</p>
                <p className="text-xs text-gray-600">{p.specification}</p>
              </div>
            ))}
          </div>
        </div>
      )}
      {c.procedureSteps?.map((step) => (
        <div key={step.step} className="flex gap-3 mb-3">
          <div className="w-6 h-6 rounded-full bg-gray-900 text-white flex items-center justify-center text-xs font-bold flex-shrink-0">{step.step}</div>
          <div className="flex-1">
            <p className="text-sm">{step.action}</p>
            {step.warning && <p className="text-xs text-amber-700 bg-amber-50 px-2 py-1 rounded mt-1">⚠ {step.warning}</p>}
          </div>
        </div>
      ))}
      <div className="mt-6 pt-4 border-t text-xs text-gray-500">Review date: {c.reviewDate} · Generated by SafeSheet AI</div>
    </div>
  );
}
