const puppeteer = require('puppeteer');

/**
 * Generates a PDF from HTML content
 * Supports RTL (Arabic) via dir="rtl" in the HTML
 */
const generatePdf = async (htmlContent, options = {}) => {
  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
      ...options,
    });

    return pdf;
  } finally {
    await browser.close();
  }
};

/**
 * Builds HTML for SDS PDF export
 */
const buildSdsHtml = (sds) => {
  const isRTL = sds.language === 'ar';

  const formatContent = (content) => {
    if (!content) return '';

    if (typeof content === 'string') {
      return `<p>${content}</p>`;
    }

    if (typeof content === 'object') {
      return Object.entries(content).map(([key, value]) => {
        if (Array.isArray(value)) {
          return `
            <div class="field">
              <div class="field-label">${key.replace(/_/g, ' ')}</div>
              <ul>${value.map(v => `<li>${v}</li>`).join('')}</ul>
            </div>`;
        }

        return `
          <div class="field">
            <div class="field-label">${key.replace(/_/g, ' ')}</div>
            <div class="field-value">${value}</div>
          </div>`;
      }).join('');
    }

    return '';
  };

  const sectionsHtml = Object.entries(sds.sections || {})
    .map(([key, section], index) => {
      if (!section) return '';

      const isHazard = key === 'section2';

      return `
        <div class="section ${isHazard ? 'hazard' : ''}">
          <div class="section-header">
            <span class="section-number">Section ${index + 1}</span>
            <span class="section-title">${section.title || ''}</span>
          </div>

          ${section.confidence ? `
            <div class="confidence">
              AI Confidence: ${section.confidence}%
            </div>` : ''}

          <div class="section-body">
            ${formatContent(section.content || section)}
          </div>
        </div>
      `;
    }).join('');

  return `
<!DOCTYPE html>
<html lang="${sds.language || 'en'}" dir="${isRTL ? 'rtl' : 'ltr'}">
<head>
<meta charset="UTF-8">

<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+Arabic:wght@400;600;700&display=swap');

  body {
    font-family: ${isRTL ? "'Noto Sans Arabic'" : "'Inter'"}, sans-serif;
    font-size: 10pt;
    color: #1a1a1a;
    padding: 0;
    margin: 0;
  }

  .header {
    background: #111827;
    color: #fff;
    padding: 20px 24px;
  }

  .header h1 {
    font-size: 18pt;
    margin-bottom: 6px;
  }

  .meta {
    font-size: 9pt;
    opacity: 0.85;
  }

  .meta strong {
    font-weight: 600;
  }

  .container {
    padding: 20px 24px;
  }

  .section {
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    margin-bottom: 14px;
    overflow: hidden;
    page-break-inside: avoid;
  }

  .section-header {
    background: #f9fafb;
    padding: 10px 14px;
    display: flex;
    justify-content: space-between;
    font-weight: 600;
    font-size: 10pt;
    border-bottom: 1px solid #e5e7eb;
  }

  .section-number {
    color: #6b7280;
  }

  .section-title {
    color: #111827;
  }

  .section-body {
    padding: 12px 14px;
  }

  .field {
    margin-bottom: 8px;
  }

  .field-label {
    font-size: 9pt;
    font-weight: 600;
    color: #374151;
    margin-bottom: 2px;
  }

  .field-value {
    font-size: 9pt;
    color: #111827;
  }

  ul {
    margin: 4px 0 6px 16px;
  }

  li {
    margin-bottom: 2px;
  }

  .hazard {
    border-color: #ef4444;
  }

  .hazard .section-header {
    background: #fef2f2;
    color: #b91c1c;
  }

  .confidence {
    font-size: 8pt;
    color: #6b7280;
    padding: 6px 14px;
    border-bottom: 1px dashed #e5e7eb;
  }

  .footer {
    padding: 14px 24px;
    font-size: 8pt;
    color: #6b7280;
    border-top: 1px solid #e5e7eb;
    text-align: center;
  }

  @page {
    size: A4;
    margin: 18mm 14mm;
  }
</style>
</head>

<body>

<div class="header">
  <h1>Safety Data Sheet (SDS)</h1>
  <div class="meta">
    <strong>${sds.chemical_name || 'Unknown Chemical'}</strong><br/>
    CAS: ${sds.cas_number || 'N/A'} |
    ${sds.jurisdiction || 'GHS'} |
    ${sds.language?.toUpperCase() || 'EN'} |
    Version ${sds.version || 1}
  </div>
</div>

<div class="container">
  ${sectionsHtml}
</div>

<div class="footer">
  Generated by <strong>Enthaplix SafeSheet AI</strong><br/>
  ${new Date().toLocaleDateString()}<br/>
  This document must be reviewed by a qualified safety professional before use.
</div>

</body>
</html>
`;
};

/**
 * Builds HTML for SOP PDF export with RTL support
 */
const buildSopHtml = (sop) => {
  const isRTL = sop.is_rtl || sop.language === 'ar';

  const stepsHtml = (sop.procedure_steps || [])
    .map((step) => `
      <div class="step ${step.critical ? 'critical' : ''}">
        <div class="step-left">
          <span class="step-num">${step.step}</span>
        </div>

        <div class="step-content">
          <div class="step-title">${step.action}</div>

          ${step.warning ? `
            <div class="warning-box">
              ⚠ ${step.warning}
            </div>
          ` : ''}

        </div>
      </div>
    `).join('');

  const ppeHtml = (sop.required_ppe || [])
    .map(p => `
      <div class="ppe-card">
        <div class="ppe-name">${p.item}</div>
        <div class="ppe-spec">${p.specification}</div>
      </div>
    `).join('');

  return `
<!DOCTYPE html>
<html lang="${sop.language || 'en'}" dir="${isRTL ? 'rtl' : 'ltr'}">
<head>
<meta charset="UTF-8">

<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+Arabic:wght@400;600;700&display=swap');

body {
  font-family: ${isRTL ? "'Noto Sans Arabic'" : "'Inter'"}, sans-serif;
  font-size: 11pt;
  color: #111827;
  margin: 0;
}

/* HEADER */
.header {
  background: #111827;
  color: #fff;
  padding: 20px 24px;
}

.header h1 {
  font-size: 18pt;
}

.header-meta {
  font-size: 9pt;
  opacity: 0.85;
  margin-top: 6px;
}

/* CONTAINER */
.container {
  padding: 20px 24px;
}

/* SECTION */
.section {
  margin-bottom: 20px;
}

.section h2 {
  font-size: 12pt;
  font-weight: 600;
  border-bottom: 2px solid #111827;
  padding-bottom: 4px;
  margin-bottom: 10px;
}

/* PPE */
.ppe-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 10px;
}

.ppe-card {
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  padding: 10px;
  background: #f9fafb;
}

.ppe-name {
  font-weight: 600;
  font-size: 10pt;
}

.ppe-spec {
  font-size: 9pt;
  color: #6b7280;
}

/* STEPS */
.step {
  display: flex;
  gap: 12px;
  margin-bottom: 10px;
  padding: 12px;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.step.critical {
  border-color: #dc2626;
  background: #fef2f2;
}

.step-left {
  flex-shrink: 0;
}

.step-num {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  background: #111827;
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
}

.step.critical .step-num {
  background: #dc2626;
}

.step-title {
  font-weight: 500;
}

/* WARNING */
.warning-box {
  margin-top: 6px;
  background: #fff3cd;
  border-left: 4px solid #f59e0b;
  padding: 6px 10px;
  font-size: 9pt;
}

/* EMERGENCY */
.emergency {
  background: #fee2e2;
  border: 1px solid #dc2626;
  border-radius: 6px;
  padding: 12px;
}

.emergency p {
  margin-bottom: 6px;
}

/* FOOTER */
.footer {
  border-top: 1px solid #e5e7eb;
  margin-top: 20px;
  padding: 10px 24px;
  font-size: 8pt;
  color: #6b7280;
  text-align: center;
}

@page {
  size: A4;
  margin: 18mm 14mm;
}
</style>
</head>

<body>

<div class="header">
  <h1>Standard Operating Procedure (SOP)</h1>
  <div class="header-meta">
    <strong>${sop.title}</strong><br/>
    Chemical: ${sop.chemical_name} |
    Type: ${sop.sop_type} |
    Version: ${sop.version} |
    Effective: ${sop.effective_date}
  </div>
</div>

<div class="container">

  <div class="section">
    <h2>${isRTL ? 'معدات الحماية الشخصية' : 'Required PPE'}</h2>
    <div class="ppe-grid">${ppeHtml}</div>
  </div>

  <div class="section">
    <h2>${isRTL ? 'خطوات الإجراء' : 'Procedure Steps'}</h2>
    ${stepsHtml}
  </div>

  <div class="section">
    <h2>${isRTL ? 'إجراءات الطوارئ' : 'Emergency Procedures'}</h2>
    <div class="emergency">
      ${Object.entries(sop.emergency_procedures || {})
        .map(([k, v]) => `<p><strong>${k.replace('_', ' ').toUpperCase()}:</strong> ${v}</p>`)
        .join('')}
    </div>
  </div>

</div>

<div class="footer">
  Generated by <strong>Enthaplix SafeSheet AI</strong><br/>
  Review Date: ${sop.review_date || 'N/A'}<br/>
  This SOP must be approved by an authorized safety officer.
</div>

</body>
</html>
`;
};

module.exports = { generatePdf, buildSdsHtml, buildSopHtml };
