const computeSectionDiff = (oldSecs = {}, newSecs = {}) => {
  const changes = [];
  const keys = new Set([...Object.keys(oldSecs), ...Object.keys(newSecs)]);
  for (const sk of keys) {
    const o = oldSecs[sk];
    const n = newSecs[sk];
    if (!o && n) {
      changes.push({
        section: sk,
        section_title: n?.title || sk,
        type: "added",
        field: "entire_section",
        old_value: null,
        new_value: "Section added",
      });
      continue;
    }
    if (o && !n) {
      changes.push({
        section: sk,
        section_title: o?.title || sk,
        type: "removed",
        field: "entire_section",
        old_value: "Section removed",
        new_value: null,
      });
      continue;
    }
    const oc = o?.content || o || {};
    const nc = n?.content || n || {};
    const fkeys = new Set([...Object.keys(oc), ...Object.keys(nc)]);
    for (const f of fkeys) {
      const ov = JSON.stringify(oc[f] ?? null);
      const nv = JSON.stringify(nc[f] ?? null);
      if (ov !== nv)
        changes.push({
          section: sk,
          section_title: n?.title || sk,
          type: !oc[f] ? "added" : !nc[f] ? "removed" : "modified",
          field: f,
          field_label: f
            .replace(/_/g, " ")
            .replace(/\b\w/g, (c) => c.toUpperCase()),
          old_value: oc[f] ?? null,
          new_value: nc[f] ?? null,
        });
    }
  }
  return changes;
};

const generateChangeSummary = (changes) => {
  if (!changes.length) return "No changes detected";
  const by = {
    classification: changes.filter((c) => c.section === "section2"),
    composition: changes.filter((c) => c.section === "section3"),
    ppe: changes.filter((c) => c.section === "section8"),
    transport: changes.filter((c) => c.section === "section14"),
  };
  const parts = [];
  if (by.classification.length)
    parts.push(
      `Hazard classification updated (${by.classification.length} fields)`,
    );
  if (by.composition.length)
    parts.push(`Composition changes (${by.composition.length} fields)`);
  if (by.ppe.length) parts.push(`PPE/exposure controls updated`);
  if (by.transport.length) parts.push(`Transport information updated`);
  const other = changes.filter(
    (c) =>
      !["section2", "section3", "section8", "section14"].includes(c.section),
  );
  if (other.length) parts.push(`Other updates (${other.length} fields)`);
  return parts.join("; ") || `${changes.length} fields modified`;
};

const generateAuditReport = (sdsDoc, versions) => ({
  report_title: `Audit Trail — ${sdsDoc.chemical_name}`,
  document_id: sdsDoc.id,
  chemical_name: sdsDoc.chemical_name,
  cas_number: sdsDoc.cas_number,
  current_version: sdsDoc.version,
  current_status: sdsDoc.status,
  generated_at: new Date().toISOString(),
  generated_for: "Regulatory Inspection / ISO 45001 Audit",
  total_revisions: versions.length,
  first_created: versions[versions.length - 1]?.created_at || sdsDoc.created_at,
  last_modified: sdsDoc.updated_at,
  version_history: versions.map((v) => ({
    version: v.version,
    created_at: v.created_at,
    changed_by: v.users?.name || v.changed_by || "System",
    change_summary: v.change_summary || "Update",
  })),
  compliance_note:
    "Audit trail generated by SafeSheet AI. All version data is timestamped and tamper-evident.",
});

module.exports = {
  computeSectionDiff,
  generateChangeSummary,
  generateAuditReport,
};
